### ISSUE TITLE
Request: German localization

### ISSUE THREAD

**Issue by DasAoD** [funkydude/BFAInvasionTimer#11]
Hi.

If you want, you can change the following lines for German localization.

```
--L.alignText = "Textausrichtung"
--L.alignIcon = "Leistenicon ausrichten"
--L.bar = "Leiste"
--L.general = "Allgemeines"
--L.zoneWarnings = "Zonenwarnung"
--L.zoneWarningsDesc = "Warnmeldung in der Mitte des Bildschirms anzeigen, wenn ein Übergriff beginnt."
```
[deDE.zip](https://github.com/funkydude/BFAInvasionTimer/files/2777543/deDE.zip)

**Comment by funkydude** [comment]
Thanks but I do not download arbitrary files.
Just paste the translation here, or if you want to do it yourself:

Navigate to the deDE.lua file [here](https://github.com/funkydude/BFAInvasionTimer/blob/master/Locales/deDE.lua) or [here](https://github.com/funkydude/BFAInvasionTimer/blob/master/Options/Locales/deDE.lua) and click the edit button (looks like a pen). Then open a pull request when you're done with it.

**Comment by DasAoD** [comment]
Ok. Thanks for the hint.
I added it as .zip-file, because .lua-files are not supported for uploads.
I pasted only the translated lines but i will edit the deDE.lua file and open a pull request.

I will close this, after editing the deDE.lua file.
