### ISSUE TITLE
Request "Next" on timer

### ISSUE THREAD

**Issue by zaldor29** [funkydude/BFAInvasionTimer#16]
Your addon is awsome!!!  The only thing that would make it AWSOME!!! in my opinion is to add "Next" before the region that the next incursion will occur.  This will make it much easier to tell that there is not an active incursion especially when less than 6 hours where it can get a bit confusing.

**Comment by Kirbdawg** [comment]
I second that request!  Every time I look up and see the databroker, i have to open up my map to see if the invasion is really up or not.

**Comment by ghost** [comment]
I came here to see why the timer was wrong, displaying an invasion that isn't actually up. Now I see it's telling me that the invasion for "x" will be up in hh:mm:ss.
Please add a "Next" on the timer (like LegionInvasionTimer). e.g. "Next: Stormsong Valley"
