### ISSUE TITLE
Stuck on waiting

### ISSUE THREAD

**Issue by zaldor29** [funkydude/BFAInvasionTimer#25]
I had to delete my WTF directory and since then, the bar is stuck on waiting and never gives me a time (probably been 12 hours of game play).  I have deleted the addon and reinstalled it and still same issue.  Is there a way to force it to update?  Also, I have done and incursion since this problem started.

**Comment by funkydude** [comment]
Nothing has changed to cause such an issue. If it persists, try relogging whilst an invasion is active.

**Comment by funkydude** [comment]
No response, closing.
