### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by CrusaderEsper** [funkydude/BFAInvasionTimer#31]
`2x BFAInvasionTimer\BFAInvasionTimer-v8.2.5.lua:429: C_Timer.After duration is too large
[C]: ?
BFAInvasionTimer\BFAInvasionTimer-v8.2.5.lua:429: in function <BFAInvasionTimer\BFAInvasionTimer.lua:358>
BFAInvasionTimer\BFAInvasionTimer-v8.2.5.lua:529: in function <BFAInvasionTimer\BFAInvasionTimer.lua:462>

Locals:
(*temporary) = 26829
(*temporary) = <function> defined @BFAInvasionTimer\BFAInvasionTimer.lua:358
`
Happens on login since Tuesday October the 1st.

**Comment by funkydude** [comment]
Can you open Task Manager > click "Performance" tab > Click "CPU"
At the bottom it should say "Up time".
What is it?

After you tell me that try restarting your PC.
Does that resolve it?

**Comment by CrusaderEsper** [comment]
49:20:42:27
So... 49 days 20 hours, 42 minutes, and 27 seconds.
Not really interested in rebooting my computer right now though.

**Comment by funkydude** [comment]
Thanks for the info.
Unfortunately there's nothing further I can do until you restart your PC so I can confirm this is an uptime issue.

**Comment by funkydude** [comment]
Closing this.
It does unfortunately appear to be tied to system uptime.
I've tried to ask Blizz to fix it but it's apparently a lot of work.

Unfortunately this isn't the only thing that will break. The game itself will start showing "strangeness" as animations and internal timers start failing.
The only solution is not letting your system be up so long.

**Comment by CrusaderEsper** [comment]
I'm glad you were able to resolve it. But even without rebooting the error stopped appearing. It never appeared again after my initial report, oddly enough. I have since been forced to reboot due to power outages, so I guess it's resolved on my end as well.
