### ISSUE TITLE
Feature Request: Location Prediction

### ISSUE THREAD

**Issue by LiangYuxuan** [funkydude/BFAInvasionTimer#6]
Hello, according to [wowhead](https://www.wowhead.com/guides/battle-for-azeroth-incursions), invasions will always follow a specific order

> Vol'dun > Drustvar > Zuldazar > Tirigarde Sound > Nazmir > Stormsong Valley

So, I wonder if the location of following invasions can be added to the timetable. Thank you!

**Comment by hollo6** [comment]
I second this, would be very helpful if I happen to forget where the last one was. The order is definitely fixed and follows the pattern above.

**Comment by kanegasi** [comment]
Third.
